// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzoXdgpSXxWWUAHFo-0J3TUtpzp7TxKTM',
    appId: '1:713379395081:web:1788af2be59014f3b56ad8',
    messagingSenderId: '713379395081',
    projectId: 'lms-app-b6bf9',
    authDomain: 'lms-app-b6bf9.firebaseapp.com',
    storageBucket: 'lms-app-b6bf9.firebasestorage.app',
    measurementId: 'G-TB3HZ7293V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDg5kGnspyEELHZK_EBRCnYap58y7e6J7k',
    appId: '1:713379395081:android:8fcf947f69025905b56ad8',
    messagingSenderId: '713379395081',
    projectId: 'lms-app-b6bf9',
    storageBucket: 'lms-app-b6bf9.firebasestorage.app',
  );
}
